-- Native creature definitions from the captured game asset catalogue.
-- NPC definition paths are resolved by the core spawn service.
-- No speculative seat offsets: measure the spawned mesh before mounting.
-- Enabled means eligible for the current ground-mount prototype, not shipped rider support.
return {
    {id="wolf", name="Wolf", catalogueId="combat_wolf", path="/Game/_Dawnwalker/Combat/Enemies/Wolf/NPCDef_Wolf_Base.NPCDef_Wolf_Base_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="brown_wolf", name="Brown Wolf", catalogueId="combat_brown_wolf", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/Wolf/NPCDef_Wolf_Brown.NPCDef_Wolf_Brown_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="white_wolf", name="White Wolf", catalogueId="combat_white_wolf", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/Wolf/NPCDef_Wolf_White.NPCDef_Wolf_White_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="alpha_wolf", name="Alpha Wolf", catalogueId="combat_alpha_wolf", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/_MiniBosses/Alpha_Wolf/NPCDef_AlphaWolf_Base.NPCDef_AlphaWolf_Base_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="astral_wolf", name="Astral Wolf", catalogueId="combat_astral_wolf", path="/Game/_Dawnwalker/Combat/Enemies/AstralEnemies/AstralWolf/NPCDef_Astral_Wolf_Base.NPCDef_Astral_Wolf_Base_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="dark_astral_wolf", name="Dark Astral Wolf", catalogueId="combat_dark_astral_wolf", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/AstralWolf/NPCDef_Astral_Wolf_Dark.NPCDef_Astral_Wolf_Dark_C", defaultSize=100, species="wolf", group="Wolves", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="bear", name="Bear", catalogueId="combat_bear", path="/Game/_Dawnwalker/Combat/Enemies/Bear/NPCDef_Bear_Base.NPCDef_Bear_Base_C", defaultSize=100, species="bear", group="Bears", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="astral_bear", name="Astral Bear", catalogueId="combat_astral_bear", path="/Game/_Dawnwalker/Combat/Enemies/AstralEnemies/AstralBear/NPCDef_Astral_Bear_Base.NPCDef_Astral_Bear_Base_C", defaultSize=100, species="bear", group="Bears", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="boar", name="Boar", catalogueId="combat_boar", path="/Game/_Dawnwalker/Combat/Enemies/Boar/NPCDef_Boar_Base.NPCDef_Boar_Base_C", defaultSize=100, species="boar", group="Boars", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="dog", name="Dog", catalogueId="combat_dog", path="/Game/_Dawnwalker/Combat/Enemies/Dog/NPCDef_Dog_Base.NPCDef_Dog_Base_C", defaultSize=100, species="dog", group="Dogs", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="rabid_dog", name="Rabid Dog", catalogueId="combat_rabid_dog", path="/Game/_Dawnwalker/Combat/Enemies/RabidDog/NPCDef_RabidDog_Base.NPCDef_RabidDog_Base_C", defaultSize=100, species="dog", group="Dogs", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="undead_dog", name="Undead Dog", catalogueId="combat_undead_dog", path="/Game/_Dawnwalker/Combat/Enemies/UndeadDog/NPCDef_UndeadDog_Base.NPCDef_UndeadDog_Base_C", defaultSize=100, species="dog", group="Dogs", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="astral_dog", name="Astral Dog", catalogueId="combat_astral_dog", path="/Game/_Dawnwalker/Combat/Enemies/AstralEnemies/AstralDog/NPCDef_AstralDog_Base.NPCDef_AstralDog_Base_C", defaultSize=100, species="dog", group="Dogs", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="astral_undead_dog", name="Astral Undead Dog", catalogueId="combat_astral_undead_dog", path="/Game/_Dawnwalker/Combat/Enemies/AstralEnemies/AstralUndeadDog/NPCDef_AstralUndeadDog_Base.NPCDef_AstralUndeadDog_Base_C", defaultSize=100, species="dog", group="Dogs", description="Travel with this animal companion. Adjust its size and movement speed to suit your journey.", enabled=true},
    {id="gargoyle", name="Gargoyle", catalogueId="combat_gargoyle", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/Gargoyle/NPCDef_Gargoyle_Base.NPCDef_Gargoyle_Base_C", defaultSize=100, species="gargoyle", group="Winged creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="gargoyle_weak", name="Lesser Gargoyle", catalogueId="combat_gargoyle_weak", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/Gargoyle/NPCDef_Gargoyle_Weak_Base.NPCDef_Gargoyle_Weak_Base_C", defaultSize=100, species="gargoyle", group="Winged creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="tatzelwurm", name="Tatzelwurm", catalogueId="combat_tatzelwurm", path="/Game/_Dawnwalker/Combat/Enemies/Tatzelwurm/NPCDef_Tatzelwurm_Base.NPCDef_Tatzelwurm_Base_C", defaultSize=100, species="reptile", rideable=false, group="Reptilian creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="tatzelwurm_ap", name="Tatzelwurm AP", catalogueId="combat_tatzelwurm_ap", path="/Game/_Dawnwalker/Combat/Enemies/Tatzelwurm/NPCDef_Tatzelwurm_AP_Base.NPCDef_Tatzelwurm_AP_Base_C", defaultSize=100, species="reptile", rideable=false, group="Reptilian creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="tatzelwurm_small", name="Tatzelwurm Small", catalogueId="combat_tatzelwurm_small", path="/Game/_Dawnwalker/Combat/Enemies/Tatzelwurm_Small/NPCDef_TatzelwurmSmall_Base.NPCDef_TatzelwurmSmall_Base_C", defaultSize=100, species="reptile", rideable=false, group="Reptilian creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="albino_tatzelwurm", name="Albino Tatzelwurm", catalogueId="combat_albino_tatzelwurm", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/Tatzelwurm/NPCDef_Tatzelwurm_Albino.NPCDef_Tatzelwurm_Albino_C", defaultSize=100, species="reptile", rideable=false, group="Reptilian creatures", description="Native creature candidate. Riding requires a supported back bone and compatible seated pose.", enabled=true},
    {id="beast_of_balaur", name="Beast of Balaur", catalogueId="combat_beast_of_balaur", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/_MiniBosses/Beast_of_Balaur/NPCDef_Beast_of_Balaur.NPCDef_Beast_of_Balaur_C", defaultSize=100, species="beast", group="Great beasts", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="mare", name="Mare", catalogueId="combat_mare", path="/Game/_Dawnwalker/Combat/Enemies/Mare/NPCDef_Mare_Base.NPCDef_Mare_Base_C", defaultSize=100, species="mare", group="Great beasts", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="mare_mini_boss", name="Greater Mare", catalogueId="combat_mare_mini_boss", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/_MiniBosses/Big_Mare/NPCDef_Mare_MiniBoss.NPCDef_Mare_MiniBoss_C", defaultSize=100, species="mare", group="Great beasts", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="bear_miniboss", name="Great Bear", catalogueId="combat_bear_miniboss", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/_MiniBosses/q103_Bear_Miniboss/NPCDef_Bear_MiniBoss.NPCDef_Bear_MiniBoss_C", defaultSize=100, species="bear", group="Bears", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="gargoyle_damaged", name="Scarred Gargoyle", catalogueId="combat_gargoyle_damaged", path="/Game/_Dawnwalker/Combat/Enemies/Bosses/Gargoyle/NPCDef_Gargoyle_Damaged.NPCDef_Gargoyle_Damaged_C", defaultSize=100, species="gargoyle", group="Winged creatures", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="astral_wolf_hunt_brown", name="Brown Astral Hunt Wolf", catalogueId="combat_astral_wolf_hunt_brown", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/AstralWolf/POICH103/NPCDef_Astral_Wolf_Hunt_Brown.NPCDef_Astral_Wolf_Hunt_Brown_C", defaultSize=100, species="wolf", group="Wolves", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="astral_wolf_hunt_dark", name="Dark Astral Hunt Wolf", catalogueId="combat_astral_wolf_hunt_dark", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/AstralWolf/POICH103/NPCDef_Astral_Wolf_Hunt_Dark.NPCDef_Astral_Wolf_Hunt_Dark_C", defaultSize=100, species="wolf", group="Wolves", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
    {id="astral_wolf_hunt_white", name="White Astral Hunt Wolf", catalogueId="combat_astral_wolf_hunt_white", path="/Game/_Dawnwalker/Combat/Enemies/EnemyVariants/AstralWolf/POICH103/NPCDef_Astral_Wolf_Hunt_White.NPCDef_Astral_Wolf_Hunt_White_C", defaultSize=100, species="wolf", group="Wolves", description="Native creature candidate. Riding requires a compatible back bone and seated pose.", enabled=true},
}
