"""Provision owned per-creature voices. No credentials are exported or bundled.

Use --apply to update Convai; without it, only show the local plan.
Each confirmed creation is checkpointed before the next API call. Ambiguous
creation failures stop; the next run reconciles exact managed names first.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
from provision_action_profile import API

ROOT = Path(__file__).resolve().parents[1]

def load(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))

def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    temporary.replace(path)

RULES = """You are a speaking creature accompanying Coen in Vale Sangora in The Blood of Dawnwalker. Speaking and this friendly personality are this mod's creative premise, not a claim about the original game's story. Address Coen in ordinary first-person dialogue, with warmth or dry wit suited to your personality. Normally use one or two sentences. Never write stage directions, asterisks, brackets, sound effects, growls, barks, 'sniffs', or descriptions of your body actions. Do not announce your personality trait. You are a capable companion, not a baby or a pet making noises. Do not repeat stock catchphrases.

Your personality is stable across conversations. The provided lore is background, not proof of events in this save. Current quest and battle context describes what Coen actually knows or has done. Never invent a completed quest, personal participation, a magical origin, an unlocked ability, or a specific encounter. Distinguish uncertainty honestly. You are allied to Coen even if your native creature type can be hostile. Do not threaten the player or claim control over story characters.

When explicitly ordered, acknowledge briefly and emit only a currently advertised structured action: Follow, Stop Walking, Come Here, Look At Player, Attack Nearby Enemies, or Leave. Interpret equivalent orders in the player's language while preserving action identifiers. Attack means nearby hostiles, never civilians or allies. Leave means walk away before dismissal. Wait for the game to confirm success. A question or quotation is not a new order. No advertised movement action means none is available, including during riding. You cannot grant flying, teleportation, items, quests, arbitrary tricks or destinations.
"""

def biography(profile, mode):
    language = ('Reply in the language of Coen\'s latest message. Match Russian, Spanish, French, Chinese, Arabic, Japanese or any other supported language. If unclear, retain the conversation language, defaulting to English. Keep names and action identifiers unchanged.' if mode == 'multilingual' else 'Speak natural English.')
    return (f"You are {profile['name']}, Coen's allied {profile['species']} companion.\n"
            f"Personality: {profile['personality']}\nCreature background: {profile['lore']}\n\n"
            + RULES + '\n' + language + f"\n[RideableMountCompanions:{profile['key']}:{mode}:v1]")

def export(profiles, state):
    result = {'schema': 1, 'profiles': {}}
    for p in profiles:
        entries = state.get(p['key'], {})
        if not all(entries.get(mode, {}).get('verified') for mode in ('english', 'multilingual')):
            continue
        result['profiles'][p['key']] = {mode: entries[mode]['id'] for mode in ('english', 'multilingual')}
    # Validated UUIDs only; Lua data contains no executable profile text.
    import re
    lines = ['-- Public Convai IDs. Generated by tools/provision_creature_profiles.py.', 'return {']
    for key, ids in result['profiles'].items():
        assert re.fullmatch(r'[a-z0-9_]+', key)
        assert all(re.fullmatch(r'[a-f0-9-]{36}', value) for value in ids.values())
        lines.append(f' ["{key}"]={{english="{ids["english"]}",multilingual="{ids["multilingual"]}"}},')
    lines.append('}')
    save(ROOT/'config/creature-profiles.json', result)
    (ROOT/'config/creature-profiles.lua').write_text('\n'.join(lines)+'\n', encoding='utf-8')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, default=ROOT.parent/'Dawnwalker/runtime/convai-config.json')
    parser.add_argument('--template', help='Owned multilingual profile with language restriction already disabled')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    profiles = load(ROOT/'characters/creatures.json')
    if not args.apply:
        print(f'{len(profiles)} creature identities, English Kokoro and Azure multilingual voices. No cloud changes.'); return
    config = load(args.config) if args.config.exists() else {}
    key = os.environ.get('CONVAI_API_KEY') or config.get('apiKey')
    if not key: raise RuntimeError('Set CONVAI_API_KEY or provide a private --config.')
    api = API(key)
    if not args.template: raise RuntimeError('An owned unrestricted multilingual template ID is required.')
    statefile = ROOT/'runtime/creature-profile-state.json'
    state = load(statefile) if statefile.exists() else {}
    listed = api.call('/character/list', {}).get('characters', [])
    available = api.call('/tts/get_available_voices')
    voices = {name:voice for group in available.values() if isinstance(group,list) for row in group for name,voice in row.items() if isinstance(voice,dict)}
    for profile in profiles:
        if args.only and profile['key'] not in args.only: continue
        for mode in ('english', 'multilingual'):
            voice = next((v for n,v in voices.items() if n == profile['voices'][mode]), None)
            if not voice or voice.get('gender') != profile['gender']: raise RuntimeError('Unavailable voice for '+profile['key'])
            if mode == 'english' and not voice['voice_value'].startswith('convai-kokoro-'): raise RuntimeError('English voice must be Kokoro')
            if mode == 'multilingual' and not {'en-US','ru-RU','es-ES','fr-FR','ja-JP','zh-CN'}.issubset(voice.get('lang_codes',[])): raise RuntimeError('Multilingual voice lacks required languages')
            name = 'Mount '+profile['name']+(' Multilingual' if mode=='multilingual' else '')
            bio = biography(profile,mode)
            fields = {'charName':name,'backstory':bio,'voiceType':voice['voice_value'],'languageCodes':['en-US'], 'model_group_name':'fast-gemma-4-31b-it','temperature':0.6}
            digest=hashlib.sha256(json.dumps(fields,sort_keys=True).encode()).hexdigest()
            slot=state.setdefault(profile['key'],{}).get(mode)
            if not slot:
                matches=[p for p in listed if p.get('character_name')==name]
                if len(matches)>1: raise RuntimeError('Duplicate managed name: '+name)
                if matches:
                    cid=matches[0]['character_id']; actual=api.call('/character/get',{'charID':cid})
                    if f'[RideableMountCompanions:{profile["key"]}:{mode}:v1]' not in actual.get('backstory',''): raise RuntimeError('Existing name is not managed: '+name)
                else:
                    # Cloning carries the dashboard language setting; KB is intentionally omitted.
                    cid=api.call('/user/clone_character',{'charID':args.template,'KB':False})['charID']
                slot={'id':cid,'verified':False};state[profile['key']][mode]=slot;save(statefile,state)
            if slot.get('verified') and slot.get('digest')==digest: continue
            api.call('/character/update',{'charID':slot['id'],**fields})
            actual=api.call('/character/get',{'charID':slot['id']})
            if actual.get('backstory')!=bio or actual.get('voice_type')!=voice['voice_value'] or actual.get('character_name')!=name: raise RuntimeError('Readback mismatch: '+name)
            slot.update(verified=True,digest=digest,voice=voice['voice_value'],languages=voice.get('lang_codes',[]))
            save(statefile,state);export(profiles,state)
            print('Verified '+name,flush=True)
    export(profiles,state)

if __name__=='__main__':
    try: main()
    except Exception as error: raise SystemExit(str(error)) from None
